Branch
Alex-H1/delivery-service pull request #5
Opened 2023-01-23 15:26 UTC by Alex-H1

2023-01-23 15:53 UTC, ankochergin reviewed
also please add some meaningful name for your PR

2023-01-23 15:53 UTC, ankochergin commented on src/main/java/sql/IOrderDAO.java
> +}
add some custom method for orders here

2023-01-23 15:53 UTC, ankochergin commented on src/main/java/sql/IPackageDAO.java
> +
add some custom method for package here

2023-01-23 15:53 UTC, ankochergin commented on src/main/java/sql/IPackageTypeDAO.java
> +public interface IPackageTypeDAO extends IBaseDAO<PackageType> {
add some custom method for package type here

2023-01-24 07:39 UTC, ankochergin commented on src/main/java/xml/JAXBMain.java
> +    public static Staff unMarshall() throws JAXBException {
```suggestion
    public static Staff unmarshall() throws JAXBException {
```

2023-01-24 07:39 UTC, ankochergin commented on src/main/java/xml/JAXBMain.java
> +    }
please implement jaxb to create the same xml as I shared yesterday

2023-01-27 19:12 UTC, ankochergin requested changes
1. check that all your variable names and methods have names according to java naming convention
2. rename PR
3. work on formatting

2023-01-27 19:12 UTC, ankochergin commented on src/main/java/model/DeliveryService.java
> +    private List<Staff> Staff;
```suggestion
    private List<Staff> staff;
```

2023-01-27 19:12 UTC, ankochergin commented on src/main/java/xml/XMLValidator.java
> +    public static boolean ValidateXML(String xsdPath, String xmlPath){
```suggestion
    public static boolean validateXML(String xsdPath, String xmlPath){
```

2023-01-30 07:57 UTC, ankochergin commented on src/main/java/JSON/JacksonMain.java
> +package JSON;
package name must be lowercase

2023-01-30 07:57 UTC, ankochergin commented on src/main/java/sql/IStaffDAO.java
> +}
please be consistent in formatting. In some classes/interfaces you have empty lines above and after method and in some no empty lines. Please fix like I suggested in all classes

2023-01-30 07:57 UTC, ankochergin commented on src/main/java/sql/IStaffDAO.java
> +}
```suggestion
public interface IStaffDAO extends IBaseDAO<Staff> {

    List<Staff> getStaffByName(String name) throws SQLException;
    
}
```

2023-01-30 07:57 UTC, ankochergin commented on src/main/java/sql/IStaffDAO.java
> +}
also please add empty line between variables and methods

2023-01-31 03:17 UTC, Alex-H1 commented
Refactor and MyBatis progress

2023-02-02 03:34 UTC, Alex-H1 commented
added mybatis implementation

2023-02-02 07:13 UTC, ankochergin approved these changes

2023-02-04 21:56 UTC, Alex-H1 commented
added facad and abstract factories

2023-02-06 07:15 UTC, ankochergin commented on src/main/java/Main.java
> +//        LOG.info(companyList1);
remove comments if they are not used

2023-02-06 07:15 UTC, ankochergin commented on src/main/java/sql/util/FacadeFactory.java
> +}
I think it's pretty the same as DBFactoryGenerator, could you please think about some other usage of patterns?

2023-02-06 07:16 UTC, ankochergin commented
also please don't forget to merge PR's. We should have small PRs for every change

2023-02-06 22:28 UTC, merged